apiVersion: v1
kind: PodTemplate
metadata:
  name: skywalking-eyes
  namespace: kubesphere-devops-worker
  labels:
    jenkins.agent.pod: 'true'
  annotations:
    jenkins.agent.labels: "skywalking-eyes"
    inherit.from: "base"
    devops.kubesphere.io/displayNameEN: 'A full-featured license tool'
    devops.kubesphere.io/descriptionEN: 'A full-featured license tool'
template:
  metadata:
    name: skywalking-eyes
  spec:
    volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock
    containers:
      - name: skywalking-eyes
        image: apache/skywalking-eyes:0.4.0
        command: ["cat"]
        args: [""]
        volumeMounts:
          - name: docker
            mountPath: /var/run/docker.sock
