apiVersion: v1
kind: PodTemplate
metadata:
  name: snyk-go-1.17
  namespace: kubesphere-devops-worker
  labels:
    jenkins.agent.pod: 'true'
  annotations:
    jenkins.agent.labels: "go snyk"
    inherit.from: "base"
    devops.kubesphere.io/displayNameEN: 'Snyk Go 1.17'
    devops.kubesphere.io/descriptionEN: 'Snyk Go 1.17'
template:
  metadata:
    name: snyk-go-1.17
  spec:
    volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock
      - name: gocache
        hostPath:
          path: /var/data/jenkins_go_cache
    containers:
      - name: snyk
        image: snyk/snyk:golang-1.17
        command: ["cat"]
        args: [""]
        volumeMounts:
          - name: docker
            mountPath: /var/run/docker.sock
          - name: gocache
            mountPath: /home/jenkins/go/pkg
