pipeline {
  agent {
    node {
      label 'k3d'
    }

  }
  stages {
    stage('Setup k3d') {
      agent none
      steps {
        container('k3d') {
          sh 'k3d cluster create'
        }
      }
    }

    stage('Load CRDs') {
      agent none
      steps {
        checkout([$class: 'GitSCM', branches: [[name: '*/master']],
            extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'ks-devops'], [$class: 'CloneOption', depth: 1, noTags: false, reference: '', shallow: true]],
            userRemoteConfigs: [[url: 'https://github.com/kubesphere/ks-devops']]
        ])

        container('k3d') {
        sh '''ls -hal
kubectl apply -f ks-devops/config/crd/bases'''
        }
      }
    }

    stage('Valid') {
      agent none
      steps {
        container('k3d') {
          sh '''ls -hal

kubectl apply -f featured/steps --dry-run=client
kubectl apply -f featured/jenkins-agents --dry-run=client
kubectl apply -f featured/pipelines --dry-run=client'''
        }
      }
    }
  }

  post {
    always {
      container('k3d') {
        sh 'k3d cluster delete'
      }
    }
  }
}
