apiVersion: devops.kubesphere.io/v1alpha3
kind: ClusterStepTemplate
metadata:
  name: checkout
  labels:
    step.devops.kubesphere.io/category: "SCM"
  annotations:
    devops.kubesphere.io/displayNameZH: "Checkout"
    devops.kubesphere.io/descriptionZH: "拉取源代码，常用于拉取非 Git 仓库代码，例如 SVN 等等"
    devops.kubesphere.io/displayNameEN: "Checkout"
    devops.kubesphere.io/descriptionEN: "check out source code, often used for non-git repository, such as svn"
spec:
  runtime: dsl
  parameters:
    - name: remote
      type: string
      display: 'Repository URL'
    - name: credentialsId
      type: secret
      display: 'Credential Name'
  template: |
    {
      "arguments": [
        {
          "key": "scm",
          "value": {
            "isLiteral": false,
            "value": "[$class: 'SubversionSCM', locations: [[cancelProcessOnExternalsFail: true,  credentialsId: '{{.param.credentialsId.name}}', depthOption: 'infinity', ignoreExternalsOption: true, local: '.', remote: '{{.param.remote}}']], quietOperation: true, workspaceUpdater: [$class: 'UpdateUpdater']]"
          }
        },
        {
          "key": "poll",
          "value": {
            "isLiteral": true,
            "value": false
          }
        }
      ],
      "name": "checkout"
    }
