apiVersion: devops.kubesphere.io/v1alpha3
kind: ClusterStepTemplate
metadata:
  name: container
  labels:
    step.devops.kubesphere.io/category: "container"
  annotations:
    devops.kubesphere.io/displayNameEN: "Container switch"
    devops.kubesphere.io/descriptionEN: "Specify a container to add nested tasks to execute inside the container"
    step.devops.kubesphere.io/icon: "container"
spec:
  runtime: dsl
  parameters:
  - name: name
    type: string
    display: 'Container name in a Pod'
  template: |
    {
      "arguments": {
        "isLiteral": true,
        "value": "{{.param.name}}"
      },
      "children": [],
      "name": "container"
    }
