apiVersion: devops.kubesphere.io/v1alpha3
kind: ClusterStepTemplate
metadata:
  name: junit
  labels:
    step.devops.kubesphere.io/category: "general"
  annotations:
    devops.kubesphere.io/displayNameEN: "JUnit Report"
    devops.kubesphere.io/descriptionEN: "Prase JUnit report"
    step.devops.kubesphere.io/icon: "test"
spec:
  runtime: dsl
  parameters:
    - name: allowEmptyResults
      type: bool
      display: 'Allow rmpty results'
    - name: keepLongStdio
      type: bool
      display: 'Keep long output'
    - name: skipPublishingChecks
      type: bool
      display: 'Skip publishing checks'
    - name: testResults
      type: string
      display: 'JUnit report file path'
  template: |
    {
      "arguments": [
        {
          "key": "allowEmptyResults",
          "value": {
            "isLiteral": true,
            "value": {{.param.allowEmptyResults}}
          }
        },
        {
          "key": "keepLongStdio",
          "value": {
            "isLiteral": true,
            "value": {{.param.keepLongStdio}}
          }
        },
        {
          "key": "skipPublishingChecks",
          "value": {
            "isLiteral": true,
            "value": {{.param.skipPublishingChecks}}
          }
        },
        {
          "key": "testResults",
          "value": {
            "isLiteral": true,
            "value": "{{.param.testResults}}"
          }
        }
      ],
      "name": "junit"
    }
