apiVersion: devops.kubesphere.io/v1alpha3
kind: ClusterStepTemplate
metadata:
  name: build
  labels:
    step.devops.kubesphere.io/category: "general"
  annotations:
    devops.kubesphere.io/displayNameEN: "Pipeline trigger"
    devops.kubesphere.io/descriptionEN: "Pipeline trigger step"
    step.devops.kubesphere.io/icon: "terminal"
spec:
  runtime: dsl
  parameters:
  - name: job
    type: pipeline
    display: 'Target Pipeline name'
    required: true
  - name: quietPeriod
    type: number
    display: 'Quiet period'
    defaultValue: "0"
  - name: wait
    type: bool
    display: 'Wait for completion'
    defaultValue: "true"
  - name: propagate
    type: bool
    display: 'Propagate errors'
    defaultValue: "true"
  - name: job
    type: string
    display: 'Target Pipeline name'
    required: true
  template: |
    {
      "arguments": [
        {
          "key": "quietPeriod",
          "value": {
            "isLiteral": true,
            "value": {{.param.quietPeriod}}
          }
        },
        {
          "key": "wait",
          "value": {
            "isLiteral": true,
            "value": {{.param.wait}}
          }
        },
        {
          "key": "propagate",
          "value": {
            "isLiteral": true,
            "value": {{.param.propagate}}
          }
        },
        {
          "key": "job",
          "value": {
            "isLiteral": true,
            "value": "{{.param.job}}"
          }
        }
      ],
      "name": "build"
    }
