apiVersion: devops.kubesphere.io/v1alpha3
kind: ClusterStepTemplate
metadata:
  name: jsleep
  labels:
    step.devops.kubesphere.io/category: "general"
  annotations:
    devops.kubesphere.io/displayNameEN: "Sleep"
    devops.kubesphere.io/descriptionEN: "Pause the process for specific time"
    step.devops.kubesphere.io/icon: "clock"
spec:
  runtime: dsl
  parameters:
    - name: unit
      type: enum
      defaultValue: 'SECONDS'
      options: '[{"label":"Seconds","value":"SECONDS"},{"label":"Minutes","value":"MINUTES"},{"label":"Hours","value":"HOURS"}]'
      display: 'Unit'
    - name: time
      type: number
      display: 'Time'
  template: |
    {
      "arguments": [
        {
          "key": "time",
          "value": {
            "isLiteral": true,
            "value": {{.param.time}}
          }
        },
        {
          "key": "unit",
          "value": {
            "isLiteral": true,
            "value": "{{.param.unit}}"
          }
        }
      ],
      "name": "jsleep"
    }
