apiVersion: devops.kubesphere.io/v1alpha3
kind: ClusterStepTemplate
metadata:
  name: with-credential
  labels:
    step.devops.kubesphere.io/category: "general"
  annotations:
    devops.kubesphere.io/displayNameEN: "With credential"
    devops.kubesphere.io/descriptionEN: "Loading credential into the environment variables"
    step.devops.kubesphere.io/icon: "key"
spec:
  runtime: dsl
  parameters:
    - name: secret
      type: secret
      display: 'Credential Name'
    - name: username
      type: string
      display: 'Username Variable'
    - name: password
      type: string
      display: 'Password Variable'
  template: |
    {
      "arguments": {
        "isLiteral": false,
        "value": "${[usernamePassword(credentialsId: '{{.param.secret}}', passwordVariable: '{{.param.password}}', usernameVariable: '{{.param.username}}')]}"
      },
      "children": [],
      "name": "withCredentials"
    }
