apiVersion: devops.kubesphere.io/v1alpha3
kind: ClusterStepTemplate
metadata:
  name: withsonarqubeenv
  labels:
    step.devops.kubesphere.io/category: "review"
  annotations:
    devops.kubesphere.io/displayNameEN: "withSonarQubeEnv"
    devops.kubesphere.io/descriptionEN: "Quickly locate potential or obvious errors in your code"
    step.devops.kubesphere.io/icon: "terminal"
spec:
  runtime: dsl
  parameters:
    - name: config
      type: code
      display: 'SonarQube Config Name'
      required: true
  template: |
    {
      "arguments": {
        "isLiteral": true,
        "value": "{{.param.config}}"
      },
      "children": [],
      "name": "withSonarQubeEnv"
    }
